In [1]:
import sqlite3
import pandas as pd

In [2]:
print("SQLite Connected Successfully")

SQLite Connected Successfully

In [3]:
import sqlite3

conn = sqlite3.connect("../sql/superstore.db")

print("Database Connected Successfully")

Database Connected Successfully

In [6]:
import os

print(os.getcwd())

C:\Users\gudla\ApexPlanet_Internship\notebooks

In [7]:
import sqlite3

conn = sqlite3.connect(r"C:\Users\gudla\Downloads\superstore.db")

print("Connected to Downloads database")

Connected to Downloads database

In [8]:
import pandas as pd

pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

                 name
0  cleaned_superstore

In [9]:
query = "SELECT * FROM cleaned_superstore LIMIT 5"

df = pd.read_sql(query, conn)

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

In [10]:
query = """
SELECT
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM cleaned_superstore
GROUP BY Category
ORDER BY Total_Sales DESC
"""

result = pd.read_sql(query, conn)

result

          Category  Total_Sales
0  Office Supplies    343425.00
1        Furniture    247379.44
2       Technology    228415.35

In [11]:
query = """
SELECT
    Region,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM cleaned_superstore
GROUP BY Region
ORDER BY Total_Profit DESC
"""

result = pd.read_sql(query, conn)

result

    Region  Total_Profit
0     West      45885.51
1     East      28025.69
2    South      22150.04
3  Central       2654.65

# Task 2 Summary

## Objectives Completed

1.Imported cleaned dataset into SQLite database
2.Performed SQL data extraction and analysis
3.Executed business queries using SQL
4.Implemented Subqueries, CTEs, and Views
5.Connected Python with SQLite database
6.Executed SQL queries using Pandas

## Key Learnings

1. Database creation and management using SQLite.
2. SQL querying for business analytics.
3. Advanced SQL concepts such as Subqueries, CTEs, and Views.
4. Integration of Python with SQL databases.
5. Data extraction and analysis using Pandas.